apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.serverTLS.useLocalFiles }}
        tls-cert: {{.Files.Get .Values.serverTLS.localCertFile | quote }}
        tls-key: {{.Files.Get .Values.serverTLS.localKeyFile | quote }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--helm-repo-namespace"
            - "{{ .Release.Namespace }}"
            - "--log-level"
            - "{{ .Values.logLevel }}"
            {{- if .Values.serverTLS.useSecret }}
            - "--tls-cert-file"
            - "/etc/tls-volume/{{ .Values.serverTLS.certContentField }}"
            - "--tls-private-key-file"
            - "/etc/tls-volume/{{ .Values.serverTLS.keyContentField }}"
            {{- end }}
            {{- if .Values.serverTLS.useLocalFiles  }}
            - "--tls-cert-file"
            - "/etc/tls-volume/.cert-file"
            - "--tls-private-key-file"
            - "/etc/tls-volume/.key-file"
            {{- end }}
            {{- if and ( eq .Values.serverTLS.useLocalFiles false ) (eq .Values.serverTLS.useSecret false )}}
            - "--insecure"
            {{- end }}
          {{- with .Values.additionalArgs }}
            {{- range . }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 9001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- if or .Values.enableLogin .Values.envVars}}
          env:
          {{- if .Values.enableLogin }}
            - name: WEAVE_GITOPS_AUTH_ENABLED
              value: "true"
          {{- end }}
          {{- with .Values.envVars }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.serverTLS.useSecret .Values.serverTLS.useLocalFiles }}
          volumeMounts:
            - name: tls-volume
              readOnly: true
              mountPath: "/etc/tls-volume"
          {{- end }}
      {{- if .Values.serverTLS.useSecret }}
      volumes:
        - name: tls-volume
          secret:
            secretName: {{ .Values.serverTLS.secretName }}
      {{ end }}
      {{- if .Values.serverTLS.useLocalFiles }}
      volumes:
        - name: tls-volume
          downwardAPI:
            items:
              - path: ".cert-file"
                fieldRef:
                  fieldPath: metadata.annotations['tls-cert']
              - path: ".key-file"
                fieldRef:
                  fieldPath: metadata.annotations['tls-key']
      {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
